Code improvement
javrr-ui/SimonDice pull request #82
Opened 2021-04-08 22:23 UTC by javrr-ui

Resueltos muchos problemas pequeños detectados por el analizador de código estático, también refactoricé código duplicado.

2021-04-09 02:56 UTC, javatlacati requested changes
esos puntos de momento

2021-04-09 02:56 UTC, javatlacati commented on src/main/java/com/company/Config.java
> +        InputStream defaultFile = GameRunner.class.getClassLoader().getResourceAsStream("default.properties");
No se cierran los flujos en caso de error lo que peude corromper los archivos de configuración.

2021-04-09 02:56 UTC, javatlacati commented on src/main/java/com/company/Game.java
> +        String entrada = ent;
esta es una reasignación inútil.

2021-04-09 02:56 UTC, javatlacati commented on src/main/java/com/company/Config.java
> +            System.out.println("Couln't save settings: " + e);
esto es hacer más grande el issue #60 favor de corregirlo primero.

2021-04-09 02:56 UTC, javatlacati commented on src/main/java/com/company/GameRunner.java
> +        if (args != null && args.length > 0) {
es mejor poner las constantes del lado izquierdo de una comparación

2021-04-18 03:27 UTC, javatlacati requested changes

2021-04-18 03:27 UTC, javatlacati commented on src/main/java/com/company/GameRunner.java
> +                if (argumentos.equals("no-gui")) {
constantes del lado izquierdo de la comparación

2021-04-18 03:27 UTC, javatlacati commented on src/main/java/com/company/StringUtils.java
> +    public static Color getColorFromRGB(String propertyValue) {
Los métodos públicos deben llevar documentación

2026-01-07 16:38 UTC, merged

2026-01-15 06:09 UTC, javrr-ui commented on src/main/java/com/company/StringUtils.java
> +    public static Color getColorFromRGB(String propertyValue) {
Resolved in 69f5b4a64a839a09b120458dd3f42bd7fbb5febe

2026-01-15 06:15 UTC, javrr-ui commented on src/main/java/com/company/Config.java
> +        InputStream defaultFile = GameRunner.class.getClassLoader().getResourceAsStream("default.properties");
Resolved in: 1c17a497ed8d5ced1b70e185dd72fc36a09e9879

2026-01-15 06:17 UTC, javrr-ui commented
ward

2026-01-15 06:20 UTC, javrr-ui commented on src/main/java/com/company/Main.java
> +                if (argumentos.equals("no-gui")) {
Resolved in: 575bd2ad3df2a8a0dd5ab8e9a333b7026180fd33

2026-01-15 06:24 UTC, javrr-ui commented on src/main/java/com/company/Game.java
> +        String entrada = ent;
resolved in: bdaa2c4a44b7ca0b22d90cee56b6a1f38412f848

2026-01-15 06:39 UTC, javrr-ui commented on src/main/java/com/company/Config.java
> +            System.out.println("Couln't save settings: " + e);
resolved in: 284381097677173d9eff36455d5d2fb550bc5418

2026-01-24 04:24 UTC, javatlacati commented
LGTM!